In [1]:
##from google.colab import drive
#drive.mount('/content/drive')


![picture](https://cdn.analyticsvidhya.com/wp-content/uploads/2019/09/pytorch.png)



# Definition


PyTorch is a Python-based library used to build neural networks.

It provides two main features:

* An n-dimensional Tensor object

* Automatic differentiation for building and training neural networks


## Tensors

At its core, PyTorch is a library for processing tensors. Tensors are a specialized data structure similar to NumPy's ndarrays, except that tensors can run on GPUs (to accelerate their numeric computations). This is a major advantage of using tensors. A tensor can be a number, vector, matrix, or any n-dimensional array.

PyTorch supports multiple types of tensors, including:

1. FloatTensor: 32-bit float
2. DoubleTensor: 64-bit float
3. HalfTensor: 16-bit float
4. IntTensor: 32-bit int
5. LongTensor: 64-bit int


# Setup

In [2]:
# !conda install pytorch torchvision -c pytorch
# # or with GPU
# ! conda install pytorch torchvision cudatoolkit=10.1 -c pytorch

#https://pytorch.org/

In [3]:
import torch
print(torch.__version__)

2.1.0+cu121


# Tensor creation

### Scalar

In [4]:
t1 = torch.tensor(4)
print(t1)

tensor(4)


### 1D tensor (vector)

In [5]:
t2 = torch.tensor([1., 2, 3, 4], dtype=torch.float32)
print(t2)

tensor([1., 2., 3., 4.])


### 2D tensor (matrix)

In [6]:
t3 = torch.tensor([[5., 6],
                   [7, 8],
                   [9, 10]])

print(t3)

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


### 3D tensor

In [7]:
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19.]]])
print(t4)

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


### Tensor filled with zeros

In [8]:
a = torch.zeros(3,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Tensor filled with ones

In [9]:
a = torch.ones(3,3)
print(a)
b = torch.full((3,3),9)
print("\n\n",b)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


 tensor([[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]])


### Tensor filled with random values

In [10]:
# setting the random seed for pytorch
torch.manual_seed(42)

## torch.randn returns a tensor filled with random numbers from a normal distribution with mean `0` and variance `1`
torch.randn(3,3)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

In [11]:
# torch.randint returns a tensor filled with random integers generated uniformly
torch.randint(0, 10, (3,3))

tensor([[9, 6, 3],
        [1, 9, 3],
        [1, 9, 7]])

In [12]:
## torch.rand returns a tensor filled with random numbers from a uniform distribution on the interval `[0, 1)`
torch.rand(3,3)

tensor([[0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040]])

# Attributes of a tensor

In [13]:
a = torch.rand(3,4)
print(a, '\n')

print(f"Shape of tensor: {a.shape}")
# print(f"Shape of tensor: {a.size()}")
print(f"Data type of tensor: {a.dtype}")
print(f"Number of dimenssion: {a.ndim}")
print(f"Device tensor is stored on: {a.device}")

tensor([[0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814],
        [0.7886, 0.5895, 0.7539, 0.1952]]) 

Shape of tensor: torch.Size([3, 4])
Data type of tensor: torch.float32
Number of dimenssion: 2
Device tensor is stored on: cpu


# Torch tensors and numpy conversion

### From tensor to numpy

In [14]:
## Tensor to numpy array
a = torch.rand(3,3)
print(a, '\n')

## convert a into numpy array b
b = a.numpy()
print(b, '\n')

## update the tensor a by adding a value to it
b +=2
print(a, '\n')

tensor([[0.0050, 0.3068, 0.1165],
        [0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913]]) 

[[0.00504577 0.30681974 0.11648858]
 [0.91026944 0.64401567 0.70710677]
 [0.6581306  0.491302   0.89130414]] 

tensor([[2.0050, 2.3068, 2.1165],
        [2.9103, 2.6440, 2.7071],
        [2.6581, 2.4913, 2.8913]]) 



Note: if the tensor a is on the cpu and not the gpu, then both a and b will share/point to the same memory

### From numpy to tensor

In [15]:
# torch.set_printoptions(precision=8)
import numpy as np

a = np.random.rand(3,3)
print(a, '\n')

## convert array a into tensor b
#.clone is used to make a copy
b = torch.from_numpy(a).clone()
print(b, '\n')
a += 2
print(b, '\n')
print(a)

[[0.72375342 0.513265   0.64274646]
 [0.62190288 0.39696203 0.19751931]
 [0.86522529 0.09682548 0.71615699]] 

tensor([[0.7238, 0.5133, 0.6427],
        [0.6219, 0.3970, 0.1975],
        [0.8652, 0.0968, 0.7162]], dtype=torch.float64) 

tensor([[0.7238, 0.5133, 0.6427],
        [0.6219, 0.3970, 0.1975],
        [0.8652, 0.0968, 0.7162]], dtype=torch.float64) 

[[2.72375342 2.513265   2.64274646]
 [2.62190288 2.39696203 2.19751931]
 [2.86522529 2.09682548 2.71615699]]


### Move tensor to a specific  GPU/CPU device

In [16]:
import torch

In [17]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
a = torch.ones(2, device=device)

In [18]:
#Move to GPU if available
if torch.cuda.is_available():
  device = torch.device('cuda')
  x = torch.ones(5, device=device)
  y = torch.ones(5).to(device)
  z = x+y

#z.cpu().numpy()

Note: if we want to convert the z below deirectly to numpy (z.numpy()), this will return an error, because numpy can only handle cpu tensors; So we wil have to bring first z to cpu first and later on do the convertion

In [19]:
z.to("cpu").numpy()
z.cpu().numpy()

array([2., 2., 2., 2., 2.], dtype=float32)

# Operations on tensors

## Standard numpy-like indexing and slicing

In [20]:
a =  torch.randint(0, 10, (4,3))
print(a, '\n')

print(a[0,0])
print(f"First row: {a[0]}")
print(f"First column: {a[:, 0]}")
print(f"Last column: {a[:, -1]}")
a[:,1] = 0
print(a)

tensor([[8, 6, 0],
        [0, 0, 0],
        [1, 3, 0],
        [1, 1, 7]]) 

tensor(8)
First row: tensor([8, 6, 0])
First column: tensor([8, 0, 1, 1])
Last column: tensor([0, 0, 0, 7])
tensor([[8, 0, 0],
        [0, 0, 0],
        [1, 0, 0],
        [1, 0, 7]])


### Exercise 1

Consider the array x below and reply to the following questions:
1. Convert x to a tensor
2. Get the attributes of the obtained tensor
3. Get the first element in the second dim of the second block (9)
4. select the third row in each block

In [21]:
import numpy as np

In [22]:
x = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]],
                      [[9, 10], [11, 12], [13, 14], [15, 16]],
                      [[17, 18], [19, 20], [21, 22], [23, 24]]])
print(x)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]


In [23]:
## WRITE YOUR CODE HERE ##

x = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]],
                      [[9, 10], [11, 12], [13, 14], [15, 16]],
                      [[17, 18], [19, 20], [21, 22], [23, 24]]])

x = torch.from_numpy(x.astype("float32"))

print("\n\n Shape:", x.shape)
print(f"\n\n Data type of tensor: {x.dtype}")
print(f"\n\n Number of dimenssion: {x.ndim}")
print(f"\n\n Device tensor is stored on: {x.device}")

print("\n\n First element in the second dim of the second block",x[1,0,0])

print("\n\n Third row of each block \n", x[:,2,:])




 Shape: torch.Size([3, 4, 2])


 Data type of tensor: torch.float32


 Number of dimenssion: 3


 Device tensor is stored on: cpu


 First element in the second dim of the second block tensor(9.)


 Third row of each block 
 tensor([[ 5.,  6.],
        [13., 14.],
        [21., 22.]])


## Arithmetic operations

### Addition, substraction,  division

For addition, substraction and division we can either use torch.add, torch.sub, torch.div or +,  - and /

In [24]:
torch.manual_seed(42)
a = torch.randn(3,3)
b = torch.randn(3,3)
print(a, '\n')
print(b)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]]) 

tensor([[ 0.2674,  0.5349,  0.8094],
        [ 1.1103, -1.6898, -0.9890],
        [ 0.9580,  1.3221,  0.8172]])


In [25]:
## compute sum of a and b
print(a + b) #torch.add(a,b)

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]])


In [26]:
## compute a -b
a - b #torch.sub(a,b)

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]])

In [27]:
##compute a / b
a / b #torch.div(a, b)

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])

In [28]:
xy=torch.tensor([[1,2,3],[4,2,1],[4,6,5]])
print(xy,"\n\n")
torch.sum(xy, dim=1)

tensor([[1, 2, 3],
        [4, 2, 1],
        [4, 6, 5]]) 




tensor([ 6,  7, 15])

### Multiplication



#### Elementwise multiplication

In [29]:
##
a * b

tensor([[ 0.0900,  0.0689,  0.1898],
        [ 0.2557,  1.8974,  0.1843],
        [ 2.1154, -0.8435,  0.3773]])

#### matrix multiplication

In [30]:
##using torch.mm
torch.mm(a, b)

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])

In [31]:
##using torch.matmul
torch.matmul(a,b)

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])

In [32]:
##using @
a @ b

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])

## Reshape, Transpose, concatenate, flatten  and squeeze tensors

### Reshaping

In [33]:
torch.manual_seed(42)

a = torch.randn(3,4)
print(a.shape)

b = a.reshape(-1, 1) #a.view(-1,1)
print(b.shape)

c = a.reshape(6,2)
print(c.shape)

torch.Size([3, 4])
torch.Size([12, 1])
torch.Size([6, 2])


### Transpose

In [34]:
a_t = a.T #torch.t(a)
print(a_t.shape)

torch.Size([4, 3])


### Concatenating

In [35]:
print(a)
print(b)

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])
tensor([[ 0.3367],
        [ 0.1288],
        [ 0.2345],
        [ 0.2303],
        [-1.1229],
        [-0.1863],
        [ 2.2082],
        [-0.6380],
        [ 0.4617],
        [ 0.2674],
        [ 0.5349],
        [ 0.8094]])


In [36]:
b = torch.randn(1, 4)
print(b.shape)
concat = torch.cat((a, b),dim=0)
print(concat.shape)

torch.Size([1, 4])
torch.Size([4, 4])


### Flattening

In [37]:
flat_vect = a.flatten()
print(flat_vect)
flat_vect.shape

tensor([ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380,
         0.4617,  0.2674,  0.5349,  0.8094])


torch.Size([12])

### Squeeze a tensor


To compress tensors along their singleton dimensions we can use the .squeeze() method and use the .unsqueeze() method to do the opposite.

In [38]:
x = torch.randn(1, 10)
y = x.squeeze()
torch.unsqueeze(y,1).shape

torch.Size([10, 1])

## In-place operations

In [39]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(y, '\n')
y.add_(x)
x.sub_(y)

print(y, '\n')
print(x)

tensor([[0.6581, 0.4913],
        [0.8913, 0.1447]]) 

tensor([[0.7746, 1.4016],
        [1.5353, 0.8518]]) 

tensor([[-0.6581, -0.4913],
        [-0.8913, -0.1447]])


## Get the value of a tensor

In [40]:
x = torch.rand(5,3)
print(x)
print(x[1,1])
print(x[1,1].item())

tensor([[0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958],
        [0.9147, 0.2036, 0.2018],
        [0.2018, 0.9497, 0.6666],
        [0.9811, 0.0874, 0.0041]])
tensor(0.6532)
0.6532081365585327


# Exercise 2:

* Create two random tensors of shape (4, 3) and send them both to the GPU. Set torch.manual_seed(1234) when creating the tensors.
* Perform a matrix multiplication on these two tensors;
* Convert the result to a Numpy array.

In [41]:
torch.manual_seed(1267)
p= torch.rand(4,3).cuda()
q= torch.rand(4,3).cuda()

(p @ q.T).cpu().numpy()

array([[1.0074552 , 0.820251  , 0.30270562, 0.7051707 ],
       [0.82832307, 0.7786733 , 0.41183573, 0.7812822 ],
       [0.5338888 , 0.48762035, 0.19276229, 0.47070006],
       [0.99513316, 0.92298293, 0.07306572, 0.87217146]], dtype=float32)

In [42]:
## WRITE YOUR CODE HERE ##
torch.manual_seed(1234)

x = torch.rand(4,3).cuda()
y = torch.rand(4,3).cuda().reshape(3,4)

results = x @ y

print("Matrix multiplication: \n",results )

print("\n\n Matrix multiplication: \n",results.cpu().numpy() )


Matrix multiplication: 
 tensor([[0.2927, 0.3668, 0.1702, 0.4772],
        [0.7219, 0.5525, 0.2948, 0.7335],
        [0.5780, 0.5550, 0.2979, 0.8017],
        [0.8177, 0.9581, 0.4231, 1.1534]], device='cuda:0')


 Matrix multiplication: 
 [[0.29268736 0.36680323 0.17024472 0.4771937 ]
 [0.7218741  0.5524542  0.29480472 0.73353696]
 [0.5780421  0.5550151  0.29789034 0.8017217 ]
 [0.8176781  0.95810586 0.42312598 1.1534454 ]]


# Exercise 3:

Create a function that takes in a square matrix A and returns a 2D tensor consisting of a flattened A with the index of each element appended to this tensor in the row dimension, e.g.,



 \begin{equation*}
 A=
 \begin{bmatrix}
  2 & 3 \\
  4 & -2
\end{bmatrix}, \ \
output = \begin{bmatrix}
  0 & 2 \\
  1 & 3 \\
  2 & 4 \\
  3 & -2
\end{bmatrix}
\end{equation*}


In [43]:
def function_concat(A):
  """
  This function takes in a square matrix A and returns a 2D tensor
  consisting of a flattened A with the index of each element
  appended to this tensor in the row dimension.

  Args:
    A: torch.Tensor

  Returns:
    output: torch.Tensor
  """
  if A.shape[0]==A.shape[1]:

    # TODO flatten A
    A_flatten = A.flatten().reshape(-1,1)
    # TODO create the idx tensor to be concatenated to A
    idx_tensor = torch.tensor(np.arange(len(A_flatten))).reshape(-1,1)
    # TODO concatenate the two tensors
    output = torch.cat((idx_tensor,A_flatten),dim=1)
  else:
    return "A not a square matrix"

  return output

In [44]:
## TEST YOUR CODE HERE ##
A = torch.tensor([[2,3,3],[4,-2,5],[4,2,4]])

function_concat(A)

tensor([[ 0,  2],
        [ 1,  3],
        [ 2,  3],
        [ 3,  4],
        [ 4, -2],
        [ 5,  5],
        [ 6,  4],
        [ 7,  2],
        [ 8,  4]])

# Exercise 4:

Write a function to check device-compatiblity with computations. Fill the missing part in the code below.

Note: You have to set the device when creating each tensor.

In [45]:
import time

In [46]:
torch.full((2,2),2).dtype


torch.int64

In [47]:
def cpu_gpu(dim, device):
  """
  Function to check device-compatiblity with computations

  Args:
    dim: Integer
    device: String ("cpu" or "cuda") or torch.device('cpu'), torch.device('cuda')

  Returns: the execution time

  """

  # TODO: create 2D tensor filled with uniform random numbers in [0,1), dim x dim
  x = torch.rand(dim,dim).to(device)
  # TODO: create 2D tensor filled with uniform random numbers in [0,1), dim x dim
  y = torch.rand(dim,dim).to(device)
  # TODO: create 2D tensor filled with the scalar value 2, dim x dim

  #z =2*(torch.ones((dim,dim))).to(device)

  z =torch.full((dim,dim),float(2)).to(device)

  start = time.time()
  # elementwise multiplication of x and y
  a = x * y
  # matrix multiplication of x and z
  b = x @ z #.astype("float342"))
  return time.time()-start

In [48]:
##  TEST YOUR CODE HERE ##

dim=10000
print(f"Execution time when using the cpu: {cpu_gpu(dim, device='cpu')}")

Execution time when using the cpu: 26.300376892089844


In [49]:
print(f"Execution time when using the gpu: {cpu_gpu(dim, device='cuda')}")

Execution time when using the gpu: 0.016605615615844727


#### Comment the results

# Extra reading

https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html
